#!/bin/bash

echo "Installing dependencies..."
echo "are you on a computer with sudo access? (y/n)"
read sudo_access

if [ "$sudo_access" == "y" ]; then
    which apt >/dev/null 2>&1
    if [ $? -eq 0 ]
    then

    # Updating the package list
    echo "Updating the package list..."
    sudo apt-get update

    # install gcc-10 and g++-10
    dpkg -s gcc-10 > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "gcc-10 not found. Attempting to install..."

        sudo apt-get install -y gcc-10

        if [ $? -eq 0 ]; then
            echo "gcc-10 installed successfully."
        else
            echo "Failed to install gcc-10. Please install it manually."
        fi
    else
        echo "gcc-10 is already installed."
    fi

    dpkg -s g++-10 > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "g++-10 not found. Attempting to install..."

        sudo apt-get install -y g++-10

        if [ $? -eq 0 ]; then
            echo "g++-10 installed successfully."
        else
            echo "Failed to install g++-10. Please install it manually."
        fi
    else
        echo "g++-10 is already installed."
    fi

    # Check if cpprestsdk is installed
    dpkg -s libcpprest-dev > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "cpprestsdk not found. Attempting to install..."

        # Attempt to install cpprestsdk
        sudo apt-get install -y libcpprest-dev

        if [ $? -eq 0 ]; then
            echo "cpprestsdk installed successfully."
        else
            echo "Failed to install cpprestsdk. Please install it manually."
        fi
    else
        echo "cpprestsdk is already installed."
    fi

    # Install SQLite3 SDK
    dpkg -s libsqlite3-dev > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "SQLite3 SDK not found. Attempting to install..."

        sudo apt-get install -y libsqlite3-dev

        if [ $? -eq 0 ]; then
            echo "SQLite3 installed successfully."
        else
            echo "Failed to install SQLite3. Please install it manually."
        fi
    else
        echo "SQLite3 is already installed."
    fi

    # Install CMake
    dpkg -s cmake > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "cmake not found. Attempting to install..."

        sudo apt-get install -y cmake

        if [ $? -eq 0 ]; then
            echo "cmake installed successfully."
        else
            echo "Failed to install cmake. Please install it manually."
        fi
    else
        echo "cmake is already installed."
    fi

    # Install Sodium
    dpkg -s libsodium-dev > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "Sodium lib not found. Attempting to install..."

        sudo apt-get install -y libsodium-dev

        if [ $? -eq 0 ]; then
            echo "Sodium installed successfully."
        else
            echo "Failed to install sodium. Please install it manually."
        fi
    else
        echo "sodium is already installed."
    fi

    # Install Qt and Wayland
        dpkg -s qt6-base-dev > /dev/null 2>&1
        if [ $? -ne 0 ]; then
            echo "Qt not found. Attempting to install..."
            sudo apt-get install -y qt6-base-dev qt6-wayland

            if [ $? -eq 0 ]; then
                echo "Qt installed successfully."
            else
                echo "Failed to install Qt. Please install it manually."
            fi
        else
            echo "Qt is already installed."
        fi

    else
        echo "This script is only for Ubuntu/Debian based systems."
        exit 1
    fi
else
    echo "are you on a computer from the university? (y/n)"
    read university_computer
fi

if [ "$university_computer" == "y" ]; then
    echo "installing dependencies locally..."
    cd lib
    sh ./setup_libs_unif.sh
else if [ "$university_computer" == "n" ]; then
    echo "Please install the dependencies manually."
fi  

fi
